on:
  repository_dispatch:
    types: [icp_domain_scan]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo python -m pip install requests
      - name: install gov_icp
        run: |
          curl -O https://raw.githubusercontent.com/lisa-hue/test-action/main/gov_icp.py

      - name: gov_icp run
        run: |
          sudo python gov_icp.py -c ${{ github.event.client_payload.company_name }} -u ${{ github.event.client_payload.url }} -uid ${{ github.event.client_payload.uuid }} -sid ${{ github.event.client_payload.scan_id }}
