on:
  repository_dispatch:
    types: [port_scan]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install ubuntu core 
        run: |
          sudo apt install nmap -y
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: install portScan
        run: |
          curl -O https://raw.githubusercontent.com/lisa-hue/test-action/main/port_scan.py
          python -m pip install requests
          python -m pip install python-nmap
      - name: port_scan run
        run: |
          sudo python port_scan.py -t ${{ github.event.client_payload.ip }} -p ${{ github.event.client_payload.port }}
