on:
  repository_dispatch:
    types: [spider_scan]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install nmap -y
          sudo python -m pip install requests
          sudo python -m pip install aiohttp
          sudo python -m pip install beautifulsoup4
          sudo python -m pip install python-nmap
      - name: install spider_aiohttp
        run: |
          curl -O https://raw.githubusercontent.com/lisa-hue/test-action/main/spider_aiohttp.py
          curl -O https://raw.githubusercontent.com/lisa-hue/test-action/main/alive_scan.py
          curl -o host.txt ${{ github.event.client_payload.downloadurl }}
      - name: alive_scan run
        run: |
          sudo python alive_scan.py
      - name: spider_aiohttp run
        run: |
          sudo python spider_aiohttp.py -t url.txt -u ${{ github.event.client_payload.url }} -uid ${{ github.event.client_payload.uuid }} -sid ${{ github.event.client_payload.scan_id }}
