on:
  repository_dispatch:
    types: [sqlinj_scan]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo python -m pip install requests
      - name: install sqlinj_scan
        run: |
          curl -O https://raw.githubusercontent.com/lisa-hue/test-action/main/sqlinj_scan_github.py
          curl -O ${{ github.event.client_payload.downloadurl }}
          curl -O https://raw.githubusercontent.com/lisa-hue/test-action/main/sqlmapproject.tar.gz
          tar -zxvf sqlmapproject.tar.gz
          setsid python ./sqlmapproject-sqlmap-dcf304c/sqlmapapi.py -s &

      - name: sqlinj_scan run
        run: |
          sudo python sqlinj_scan_github.py -t ${{ github.event.client_payload.scan_id }}.txt -u ${{ github.event.client_payload.url }} -uid ${{ github.event.client_payload.uuid }} -sid ${{ github.event.client_payload.scan_id }}
          ls -ll
          cat sqlinj.txt
