on:
  repository_dispatch:
    types: [icp_zhanzhang_domain_scan]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo python -m pip install requests
          sudo python -m pip install Js2Py
      - name: install icp_zhanzhang
        run: |
          curl -O https://raw.githubusercontent.com/lisa-hue/test-action/main/zhanzhang_icp.py
          curl -O https://raw.githubusercontent.com/lisa-hue/test-action/main/generatetoken.js

      - name: icp_zhanzhang run
        run: |
          sudo python zhanzhang_icp.py -c1 ${{ github.event.client_payload.company_name1 }} -c2 ${{ github.event.client_payload.company_name2 }} -c3 ${{ github.event.client_payload.company_name3 }} -c4 ${{ github.event.client_payload.company_name4 }} -c5 ${{ github.event.client_payload.company_name5 }} -u ${{ github.event.client_payload.url }} -uid ${{ github.event.client_payload.uuid }} -sid ${{ github.event.client_payload.scan_id }}
